replicaCount: 1
deploymentName: mirror
namespace: mirror
image:
  repository: wlanboy/mirrorservice
  tag: latest
  pullPolicy: Always

hosts: 
  - mirror.tp.lan
  - mirror.gmk.lan
  - mirror.localhost

service:
  port: 8080

ingress:
  # istio | traefik | none
  controller: istio

istio:
  gateway: mirror-gateway
  gatewayNamespace: "istio-ingress"

traefik:
  entryPoints:
    - web
    - websecure

serviceEntry:
  enabled: false
  host: mirror.gmk.lan

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: mirrorapi-tls

extraVolumeMounts: []
extraVolumes: []
extraEnv: []
