name: Github Docker build and publish image
on: 
  push:
    tags:
      - '*g'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
      
    - name: Build and publish Docker Image to GitHub Packages Registry
      uses: VaultVulp/gp-docker-action@abd86dfdcd23929f6195a0fd455769a73b7276da # 1.1.7
      with:
        github-token: ${{ github.token }}
        image-name: mirrorservice
        image-tag: latest
        extract-git-tag: false
        dockerfile: Dockerfile
        build-context: .
        pull-image: false
